# Generated by Django 5.1.2 on 2024-10-14 09:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMP_Man_Apis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Date_of_joining',
            new_name='date_of_joining',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='manager_id',
            new_name='manager',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='Designation',
        ),
        migrations.AlterField(
            model_name='employee',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(55), django.core.validators.MinValueValidator(18)]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='designation',
            field=models.CharField(default='employee', max_length=150),
        ),
    ]
