# Generated by Django 5.1.2 on 2024-10-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMP_Man_Apis', '0002_rename_date_of_joining_employee_date_of_joining_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='employee_profile/'),
        ),
    ]
