# Generated by Django 5.0.5 on 2024-05-13 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='Associated_company',
            field=models.CharField(choices=[('grow', 'grow'), ('zerodha', 'zerodha'), ('upstocks', 'upstocks')]),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='Location',
            field=models.CharField(choices=[('PUN', 'Pune'), ('BAN', 'Bangalore'), ('NYC', 'NEW_YORK'), ('MUM', 'Mumbai'), ('DEL', 'Delhi'), ('HYD', 'Hyderabad')]),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='Role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('FM', 'FundManager'), ('CUST', 'Customer')]),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='contact_info',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='holdings',
            name='stock_name',
            field=models.CharField(choices=[('MSFT', 'Microsoft'), ('TATH', 'TATA_Tech'), ('AAPL', 'Apple'), ('TES', 'TESLA'), ('GOOGL', 'Google'), ('AMZ', 'AMAZON')], max_length=50),
        ),
    ]
