# Generated by Django 5.0.5 on 2024-05-13 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_alter_adminuser_associated_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='Foriegn_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='Is_Admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='Is_Customer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='Is_FundManager',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='Location',
            field=models.CharField(choices=[('MUM', 'Mumbai'), ('HYD', 'Hyderabad'), ('DEL', 'Delhi'), ('BAN', 'Bangalore'), ('NYC', 'NEW_YORK'), ('PUN', 'Pune')]),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='Role',
            field=models.CharField(choices=[('CUST', 'Customer'), ('FM', 'FundManager'), ('Admin', 'Admin')]),
        ),
        migrations.AlterField(
            model_name='holdings',
            name='stock_name',
            field=models.CharField(choices=[('AAPL', 'Apple'), ('TATH', 'TATA_Tech'), ('AMZ', 'AMAZON'), ('GOOGL', 'Google'), ('MSFT', 'Microsoft'), ('TES', 'TESLA')], max_length=50),
        ),
    ]
