# Generated by Django 5.0.5 on 2024-05-13 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_rename_is_fundmanager_adminuser_is_fm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='Associated_company',
            field=models.CharField(choices=[('upstocks', 'upstocks'), ('zerodha', 'zerodha'), ('grow', 'grow')]),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='Foriegn_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='Location',
            field=models.CharField(choices=[('NYC', 'NEW_YORK'), ('HYD', 'Hyderabad'), ('DEL', 'Delhi'), ('PUN', 'Pune'), ('MUM', 'Mumbai'), ('BAN', 'Bangalore')]),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='Role',
            field=models.CharField(choices=[('FM', 'FundManager'), ('Admin', 'Admin'), ('CUST', 'Customer')]),
        ),
        migrations.AlterField(
            model_name='holdings',
            name='stock_name',
            field=models.CharField(choices=[('TES', 'TESLA'), ('TATH', 'TATA_Tech'), ('AMZ', 'AMAZON'), ('AAPL', 'Apple'), ('MSFT', 'Microsoft'), ('GOOGL', 'Google')], max_length=50),
        ),
    ]
