# Generated by Django 5.0.5 on 2024-05-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_alter_adminuser_associated_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='Associated_company',
            field=models.CharField(choices=[('grow', 'grow'), ('upstocks', 'upstocks'), ('zerodha', 'zerodha')]),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='Foriegn_id',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='Location',
            field=models.CharField(choices=[('MUM', 'Mumbai'), ('DEL', 'Delhi'), ('HYD', 'Hyderabad'), ('BAN', 'Bangalore'), ('NYC', 'NEW_YORK'), ('PUN', 'Pune')]),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='Role',
            field=models.CharField(choices=[('FM', 'FundManager'), ('CUST', 'Customer'), ('Admin', 'Admin')]),
        ),
        migrations.AlterField(
            model_name='holdings',
            name='stock_name',
            field=models.CharField(choices=[('AMZ', 'AMAZON'), ('TATH', 'TATA_Tech'), ('TES', 'TESLA'), ('MSFT', 'Microsoft'), ('GOOGL', 'Google'), ('AAPL', 'Apple')], max_length=50),
        ),
    ]
