# Generated by Django 5.0.5 on 2024-05-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_alter_adminuser_associated_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='Associated_company',
            field=models.CharField(choices=[('zerodha', 'zerodha'), ('grow', 'grow'), ('upstocks', 'upstocks')]),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='Location',
            field=models.CharField(choices=[('MUM', 'Mumbai'), ('DEL', 'Delhi'), ('PUN', 'Pune'), ('BAN', 'Bangalore'), ('HYD', 'Hyderabad'), ('NYC', 'NEW_YORK')]),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='Role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('FM', 'FundManager'), ('CUST', 'Customer')], editable=False),
        ),
        migrations.AlterField(
            model_name='holdings',
            name='stock_name',
            field=models.CharField(choices=[('TATH', 'TATA_Tech'), ('AAPL', 'Apple'), ('GOOGL', 'Google'), ('AMZ', 'AMAZON'), ('MSFT', 'Microsoft'), ('TES', 'TESLA')], max_length=50),
        ),
    ]
