# Generated by Django 5.0.5 on 2024-05-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_alter_adminuser_associated_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='Associated_company',
            field=models.CharField(choices=[('zerodha', 'zerodha'), ('upstocks', 'upstocks'), ('grow', 'grow')]),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='Location',
            field=models.CharField(choices=[('BAN', 'Bangalore'), ('PUN', 'Pune'), ('NYC', 'NEW_YORK'), ('HYD', 'Hyderabad'), ('MUM', 'Mumbai'), ('DEL', 'Delhi')]),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='Role',
            field=models.CharField(choices=[('CUST', 'Customer'), ('FM', 'FundManager'), ('Admin', 'Admin')], editable=False),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='contact_info',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='holdings',
            name='stock_name',
            field=models.CharField(choices=[('GOOGL', 'Google'), ('TATH', 'TATA_Tech'), ('AMZ', 'AMAZON'), ('TES', 'TESLA'), ('AAPL', 'Apple'), ('MSFT', 'Microsoft')], max_length=50),
        ),
    ]
