# Generated by Django 5.0.5 on 2024-05-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0008_alter_adminuser_associated_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='Associated_company',
            field=models.CharField(choices=[('upstocks', 'upstocks'), ('zerodha', 'zerodha'), ('grow', 'grow')]),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='Location',
            field=models.CharField(choices=[('BAN', 'Bangalore'), ('HYD', 'Hyderabad'), ('MUM', 'Mumbai'), ('NYC', 'NEW_YORK'), ('DEL', 'Delhi'), ('PUN', 'Pune')]),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='contact_info',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='holdings',
            name='stock_name',
            field=models.CharField(choices=[('TATH', 'TATA_Tech'), ('MSFT', 'Microsoft'), ('GOOGL', 'Google'), ('AMZ', 'AMAZON'), ('TES', 'TESLA'), ('AAPL', 'Apple')], max_length=50),
        ),
    ]
